# Generated by Django 5.2 on 2025-04-15 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicplayer', '0002_song_added_on_song_artist_alter_song_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='file',
            new_name='audio_file',
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
