# Generated by Django 5.2 on 2025-04-15 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicplayer', '0003_rename_file_song_audio_file_alter_song_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicplayer.song')),
            ],
        ),
    ]
